using Relentless;

namespace Furby.Utilities.Salon2
{
	[GameEventEnum]
	public enum SalonItemUseEvent
	{
		NONE = 0,
		HAIRSPRAY_START = 1,
		HAIRSPRAY_END = 2,
		ELECTRIC_SHAVER_START = 3,
		ELECTRIC_SHAVER_END = 4,
		HAIRBRUSH_START = 5,
		HAIRBRUSH_END = 6,
		COMB_START = 7,
		COMB_END = 8,
		LEAFBLOWER_START = 9,
		LEAFBLOWER_END = 10,
		HAIRGEL_START = 11,
		HAIRGEL_END = 12,
		HAIRDRYER_START = 13,
		HAIRDRYER_END = 14,
		CURLING_IRON_START = 15,
		CURLING_IRON_END = 16,
		RAKE_START = 17,
		RAKE_END = 18,
		TALCUM_POWDER_START = 19,
		TALCUM_POWDER_END = 20,
		TOILET_ROLL_START = 21,
		TOILET_ROLL_END = 22,
		UNDERPANTS_START = 23,
		UNDERPANTS_END = 24
	}
}
