using Relentless;

namespace Furby
{
	[GameEventEnum]
	public enum HintEvents
	{
		DeactivateAll = 0,
		Dashboard_AdultLowStatus_Hungry = 1,
		Dashboard_AdultLowStatus_Happy = 2,
		Dashboard_AdultLowStatus_Hygeine = 3,
		Dashboard_AdultLowStatus_Toilet = 4,
		Dashboard_EggEarntButDidNothingWithIt = 5,
		Incubation_MissedAnAttentionPoint = 6,
		Blender_SuggestScrollTheCarousel = 7,
		Blender_SuggestSelectFoodItem = 8,
		Blender_SuggestPressBlend = 9,
		Blender_SuggestFeedingBaby = 10,
		Salon_SuggestScrollCarousel = 11,
		Salon_SuggestSelectItem = 12,
		Salon_SuggestTurnShowerOn = 13,
		Salon_SuggestTurnShowerOff = 14,
		Salon_SuggestCoverBabyWithItem = 15,
		Furball_YouNeedToDispatchBall = 16,
		Furball_YouNeedToDefendTheGoal = 17,
		HideAndSeek_SuggestPoppingABalloon = 18,
		Singalong_SuggestPressingANote_START = 19,
		Singalong_SuggestPressingANote_END = 20,
		Singalong_SuggestActivatingSpecialMode_START = 21,
		Singalong_SuggestActivatingSpecialMode_END = 22,
		Hose_SuggestTurningWaterOn = 23,
		Hose_SuggestTurningWaterOff = 24,
		PoopStation_SuggestOpeningLid = 25,
		PoopStation_SuggestFlushingToilet = 26,
		PoopStation_SuggestRemovingSmell = 27,
		Sickbay_SuggestSelectingAnItem = 28,
		Sickbay_SuggestCombiningItems = 29,
		Sickbay_SuggestSendingCure = 30,
		Pantry_SuggestScrollingCarousel = 31,
		Pantry_SuggestSelectingFood = 32,
		Pantry_SuggestSendingFoodToFurby = 33,
		Pantry_SuggestGoingBackAfterSpitback = 34,
		Hypnotise_SuggestSwingPendulum = 35,
		PlayroomCustomize_SuggestSelectingArea = 36,
		PlayroomCustomize_SuggestScrollingCarousel_Top = 37,
		PlayroomCustomize_SuggestScrollingCarousel_Bot = 38,
		PlayroomCustomize_SuggestSelectingAnItem = 39,
		PlayroomCustomize_SuggestConfirmingChanges = 40,
		Naming_SuggestScrollingWheels = 41,
		Naming_SuggestConfirmingName = 42,
		Furball_YouNeedToDispatchBall_Attacking = 43,
		Furball_YouNeedToDispatchBall_Defending = 44,
		Furball_DispatchedBall = 45,
		Furball_DefendedTheGoal = 46,
		PlayroomCustomize_SuggestSelectingAnItem_Top = 47,
		PlayroomCustomize_SuggestSelectingAnItem_Bot = 48,
		Salon_ActionPerformed = 49,
		VoiceChanger_SuggestSelectingPotion = 50,
		VoiceChanger_SuggestSendingPotionToFurby = 51,
		VoiceChanger_SuggestGoingBack = 52,
		InputDetected = 53,
		Hose_HoseTurnedOn = 54,
		Hose_HoseTurnedOff = 55,
		Hints_PrefabInstantiated = 56,
		Hose_HoseAdjusted = 57,
		Sickbay_SuggestDiagnosis = 58,
		Incubation_SuggestManualImprint = 59,
		Incubation_SuggestManualImprint_Expired = 60,
		Furball_HitTheRebound_Start = 61,
		Furball_HitTheRebound_End = 62,
		Gifting_SuggestFlicking_Start = 63,
		Gifting_SuggestFlicking_End = 64
	}
}
