using Relentless;

namespace Furby.Playroom
{
	[GameEventEnum]
	public enum PlayroomGameEvent
	{
		EarTouchLeft = 0,
		EarTouchRight = 1,
		MouthTouch = 2,
		FootTouchLeft = 3,
		FootTouchRight = 4,
		BellyTouch = 5,
		HeadTouch = 6,
		BodyTouchLeft = 7,
		BodyTouchRight = 8,
		EyeTouchLeft = 9,
		EyeTouchRight = 10,
		BodyTickle = 11,
		EnterPlayroom = 12,
		ExitPlayroom = 13,
		MadeDizzy = 14,
		PersonalityAnim_SweetBelle_1 = 15,
		PersonalityAnim_SweetBelle_2 = 16,
		PersonalityAnim_Kooky1 = 17,
		PersonalityAnim_Kooky2 = 18,
		PersonalityAnim_ToughGirl1 = 19,
		PersonalityAnim_ToughGirl2 = 20,
		PersonalityAnim_RockStar1 = 21,
		PersonalityAnim_RockStar2 = 22,
		PersonalityAnim_Gobbler1 = 23,
		PersonalityAnim_Gobbler2 = 24,
		Customization_SequenceBegun = 25,
		Customization_ItemChanged = 26,
		Customization_ChangesApplied = 27,
		LowStatus_Hungry = 28,
		LowStatus_Neglected = 29,
		LowStatus_Dirty = 30,
		SadSinging_LeftIdleForTooLong = 31,
		SadSinging_SendingSympathyRequestToFurby = 32,
		SadSinging_ReceivedResponse = 33,
		SadSinging_NoResponse = 34,
		SadSinging_SequenceComplete = 35,
		Progression_Started = 36,
		Progression_Complete = 37,
		Progression_FXandCelebrate = 38,
		PlayInteractionVideo = 39,
		Customization_SequenceEnded = 40,
		LowStatus_StartupIsNeglected = 41,
		LowStatus_StartupNotNeglected = 42,
		LowStatus_FeelsHungry = 43,
		LowStatus_FliesPresent = 44,
		SadSinging_SequenceInterrupted = 45,
		Customization_ChangesReverted = 46,
		Interaction_Drag_EarL = 47,
		Interaction_Drag_EarR = 48,
		Interaction_Drag_FootL = 49,
		Interaction_Drag_FootR = 50,
		Customization_ChangesAppliedButStillInLowStatus = 51,
		Progression_FXandCelebrate_SpringGem = 52
	}
}
